#ifndef HEATWAVE_HWCONFIG_HPP
#define HEATWAVE_HWCONFIG_HPP

#ifdef DEBUG
#define DBG_ENABLE_DBG_ASSERT 1
#define DBG_CHECKED_HANDLES 1
#define DBG_CHECKED_ALLOCATORS 1
#else
#define DBG_ENABLE_DBG_ASSERT 0
#define DBG_CHECKED_HANDLES 0
#define DBG_CHECKED_ALLOCATORS 0
#endif

#endif // HEATWAVE_HWCONFIG_HPP
