#ifndef HEATWAVE_HWCONFIG_HPP
#define HEATWAVE_HWCONFIG_HPP

#ifdef DEBUG
#define DBG_ENABLE_DBG_ASSERT
#define DBG_CHECKED_HANDLES
#define DBG_CHECKED_ALLOCATORS
#endif

#endif // HEATWAVE_HWCONFIG_HPP
